################################
##  Addressible places
################################

--- address
---

- condition:
    - place = city
  action:
    - load_city:
        name:           %place
        region:         %region
        country:        %country


- condition:
    - place = town
  action:
    - load_city:
        name:           %place
        region:         %region
        country:        %country


- condition:
    - place = suburb
  action:
    - load_suburb:
        name:           %place
