################################
##  Addressible places
################################

--- address
---

- condition:
    - place = city
  action:
    - load_city:
        name:           %placename
        region:         %regionname
        country:        %countryname


- condition:
    - place = town
  action:
    - load_city:
        name:           %placename
        region:         %regionname
        country:        %countryname


- condition:
    - place = suburb
  action:
    - load_suburb:
        name:           %placename
