################################
##  Addressible places
################################

--- address
---

- condition:
    - place = city
  action:
    - load_city:
        CityName:     %placename
        RegionName:   %regionname
        CountryName:  %countryname


- condition:
    - place = town
  action:
    - load_city:
        CityName:     %placename
        RegionName:   %regionname
        CountryName:  %countryname


- condition:
    - place = suburb
  action:
    - load_suburb:
        SuburbName:   %placename
